name: macOS build with clang and GCC

on:
  push:
  pull_request:

jobs:
  install_gcc9_cmake:
    name: install with gcc@9.3.0 (CMake)
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install GCC with brew
      run: |
        brew install cmake
        brew install gcc
        gcc-9 --version
    - name: compile
      run: |
        export CC=$(which gcc-9)
        export CXX=$(which g++-9)
        mkdir build && cd build
        cmake ..
        make VERBOSE=ON
#        make check

  install_clang_cmake:
    name: install with AppleClang 11.0 (CMake)
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install autotools with brew
      run: |
        brew install cmake
    - name: compile
      run: |
        mkdir build && cd build
        cmake ..
        make VERBOSE=ON
#        make check

  install_gcc9_autotools:
    name: install with gcc@9.3.0 (Autotools)
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install GCC with brew
      run: |
        brew install automake
        brew install gcc
        gcc-9 --version
    - name: compile
      run: |
        export CC=$(which gcc-9)
        export CXX=$(which g++-9)
        sh autogen.sh
        ./configure
        make
#        make check

  install_clang_autotools:
    name: install with AppleClang 11.0 (Autotools)
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: install autotools with brew
      run: |
        brew install automake
    - name: compile
      run: |
        sh autogen.sh
        ./configure
        make
#        make check
